In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
    
engine = create_engine('mysql+pymysql://root@localhost:3306/music_development')
music = engine.connect()
data_path = '../data/'

In [2]:
sql = '''
SELECT * FROM songs
WHERE rank BETWEEN 1060 AND 1069
'''
songs = pd.read_sql(sql, music)
songs

,id,rank,name,artist_id,length,location,genre_id,youtube_code,released_date,rating,website
0,550,1060,Don't Stop Believin',303,251,Journey_-_Don_t_Stop_Believin_.mp3,1,VcjzHMhBtf0,2025-12-02,0,0
1,551,1061,Girls Just Want To Have Fun,304,266,Cyndi_Lauper_-_Girls_Just_Want_To_Have_Fun.mp3,1,PIb6AZdTr-A,2025-12-02,0,0
2,552,1062,With A Little Help From My Friends,306,541,Joe_Cocker_-_With_A_Little_Help_From_My_Friend...,1,rr0X1wJ7lx8,2025-12-03,0,0
3,553,1063,What A Wonderful World,307,145,Louis_Armstrong_-_What_A_Wonderful_World.mp3,7,CaCSuzR4DwM,2025-12-04,0,0
4,554,1064,Massachusetts,110,174,Bee_Gees_-_Massachusetts.mp3,1,FuoWykVNwyI,2025-12-06,0,0
5,555,1065,Don't Worry Be Happy,308,231,Bobby_McFerrin_-_Don_t_Worry_Be_Happy.mp3,1,d-diB65scQU,2025-12-06,0,0
6,556,1066,Karma Chameleon,309,238,Culture_Club_-_Karma_Chameleon.mp3,1,JmcA9LIIXWw,2025-12-06,0,0
7,557,1067,Yellow,125,272,Coldplay_-_Yellow.mp3,1,yKNxeF4KMsY,2025-12-06,0,0
8,558,1068,Streets of London,310,243,Ralph_McTell_-_Streets_of_London.mp3,1,SpLMpu2-MXo,2025-12-07,0,0

In [5]:
songs.dtypes

id                int64
rank              int64
name             object
artist_id         int64
length            int64
location         object
genre_id          int64
youtube_code     object
released_date    object
rating            int64
website           int64
dtype: object

In [7]:
sql = '''
SELECT * FROM songs
WHERE name LIKE "yesterday"
'''
songs = pd.read_sql(sql, engine)
songs

,id,rank,name,artist_id,length,location,genre_id,youtube_code,released_date,rating,website
0,16,13,Yesterday,1,127,Beatles_The_-_Yesterday.mp3,12,fCV9oqtwyVA,1965-09-01,5,0

In [9]:
sql = '''
SELECT * FROM songs
WHERE name LIKE "yesterday"
'''
songs = pd.read_sql(sql, engine)
song = songs.iloc[0]
songId = song['id']
songId

16

In [11]:
# Method 2: Direct string printing with proper formatting
sql = f"""
SELECT id, song_id, content 
FROM lyrics 
WHERE song_id = {songId}
"""
lyric = pd.read_sql(sql, engine)
lyric

   id  song_id                                            content
0  12       16  5|Yesterday, \r\n9|all my troubles seemed so f...

In [13]:
lyric.dtypes

id          int64
song_id     int64
content    object
dtype: object

In [8]:
sqlUpd = text("""UPDATE lyrics SET song_id = 531 WHERE id = 450""")
print(sqlUpd)

UPDATE lyrics SET song_id = 531 WHERE id = 450

In [9]:
rp = music.execute(sqlUpd, {'song_id': songId})

# Print the number of rows affected
print("Rows updated:", rp.rowcount)

Rows updated: 1