### Must check that there are data for all sector

### Input file: name-ttl.csv
### Output files: Price.csv, Price-Today.csv

In [3]:
import glob
import os
import pandas as pd
from datetime import date, timedelta, datetime
from pandas.tseries.offsets import *
from sqlalchemy import create_engine

engine = create_engine("sqlite:///c:\\ruby\\port_lite\\db\\development.sqlite3")
conlite = engine.connect()

##pd.reset_option('display.max_rows')
pd.options.display.float_format = '{:.2f}'.format
pd.options.display.max_rows = 120

today = date.today()
yesterday = today - timedelta(days=1)
print(today, yesterday)

2025-12-08 2025-12-07

In [4]:
# convert the timedelta object to a BusinessDay object
num_business_days = BDay(2)
yesterday = today - num_business_days
print(f'today: {today}')
yesterday = yesterday.date()
print(f'yesterday: {yesterday}')

today: 2025-12-08
yesterday: 2025-12-04

In [5]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2025-12-08 19:59:46

### Restart & Run All Cells

In [7]:
# Get the user's home directory
user_path = os.path.expanduser('~')
# Get the current working directory
current_path = os.getcwd()
# Derive the base directory (base_dir) by removing the last folder ('Daily')
base_path = os.path.dirname(current_path)
#C:\Users\PC1\OneDrive\A5\Data
dts_path = os.path.join(user_path, "Downloads", "Datasets")
#print(f"Datasets path: {dts_path}")
dat_path = os.path.join(base_path, "Data")
#C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data>
god_path = os.path.join(user_path, "OneDrive","Imports","santisoontarinka@gmail.com - Google Drive","Data")
#C:\Users\PC1\iCloudDrive\data
icd_path = os.path.join(user_path, "iCloudDrive", "Data")
#C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data
osd_path = os.path.join(user_path, "OneDrive","Documents","obsidian-git-sync","Data")

In [8]:
print("User path:", user_path)
print(f"Current path: {current_path}")
print(f"Base path: {base_path}")
print(f"Datasets path : {dts_path}") 
print(f"Data path : {dat_path}") 
print(f"Google Drive path : {god_path}")
print(f"iCloudDrive path : {icd_path}") 
print(f"Obsidian path : {osd_path}")

User path: C:\Users\PC1
Current path: C:\Users\PC1\OneDrive\A5\Daily
Base path: C:\Users\PC1\OneDrive\A5
Datasets path : C:\Users\PC1\Downloads\Datasets
Data path : C:\Users\PC1\OneDrive\A5\Data
Google Drive path : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data
iCloudDrive path : C:\Users\PC1\iCloudDrive\Data
Obsidian path : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data

In [9]:
colu = 'Symbol Last Change %Change Open High Low'.split()
vol = 'Total Volume'
colu.append(vol)
val = 'Total Value (k)'
colu.append(val)
colu

['Symbol',
 'Last',
 'Change',
 '%Change',
 'Open',
 'High',
 'Low',
 'Total Volume',
 'Total Value (k)']

In [10]:
format_dict = {'Bid Size':'{:,}','Offer Size':'{:,}',
              'Last':'{:,.2f}','Open':'{:,.2f}','High':'{:,.2f}','Low':'{:,.2f}','Bid':'{:,.2f}','Offer':'{:,.2f}',
              'Total Volume':'{:,}','Total-Volume':'{:,}','Total Value (k)':'{:,.3f}','Total-Value-(k)':'{:,.3f}',
              'TR Volume':'{:,}','TR Value (k)':'{:,.3f}',               
              'Change':'{:,.2f}','%Change':'{:.2f}%'}

### If use style.format(format_dict), number of maximum rows will be ineffective

In [12]:
### SET100 b
file_name = "StockQuotation.xlsx"
input_file = os.path.join(dts_path, file_name)
df_S100 = pd.read_excel(input_file, header=8)
df_S100 = df_S100[df_S100['Total Volume'] != '-']
#df_S100[colu].sort_values(['%Change'],ascending=[False])
df_S100[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.13,-0.04,-3.42,1.17,1.17,1.13,57725648,66212.38
1,ADVANC,305.00,-1,-0.33,307.00,309.00,304.00,4097064,1253890.25
2,AEONTS,96.25,0.50,0.52,96.00,97.75,95.75,270550,26139.12
3,AMATA,16.10,-0.20,-1.23,16.20,16.20,15.90,11451937,183678.55
4,AOT,53.00,-,-,53.50,55.75,52.75,76447306,4133907.16

In [13]:
df_S100.query('Symbol == ("BCH","IVL","JMART","JMT","PTTGC","RCL","SCC","STA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
12,BCH,-,9.90,-0.05,-0.50,9.95,10.10,9.90,-,0.00,4641866,46179.42,628100,9.90,9.95,428900
47,IVL,-,15.20,-0.10,-0.65,15.30,15.40,15.00,-,0.00,17458918,264310.12,182900,15.10,15.20,383300
49,JMART,-,6.75,-0.15,-2.17,6.90,6.90,6.70,-,0.00,2935827,19875.88,481000,6.70,6.75,372900
50,JMT,-,8.45,-0.35,-3.98,8.75,8.85,8.45,-,0.00,6090173,52564.86,290500,8.45,8.50,985000
71,PTTGC,-,20.00,-0.30,-1.48,20.10,20.30,20.00,16000,320.00,9774635,196537.06,64600,20.00,20.10,95400
74,RCL,-,26.75,-0.50,-1.83,27.25,27.25,26.75,-,0.00,1888603,50885.54,68800,26.75,27.00,248000
77,SCC,-,180.50,-3.50,-1.90,183.50,186.00,180.00,9000,1624.50,3029387,551679.69,38000,180.50,181.00,21300
84,STA,-,11.70,-0.10,-0.85,11.80,11.90,11.60,-,0.00,1471168,17286.17,32800,11.60,11.70,141300

In [14]:
### sSET 1
file_name = "StockQuotation (1).xlsx"
input_file = os.path.join(dts_path, file_name)
df_sSET = pd.read_excel(input_file, header=8)
df_sSET = df_sSET[df_sSET['Total Volume'] != '-']
df_sSET[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,A5,1.83,-0.01,-0.54,1.83,1.83,1.76,4916,8.92
1,AAI,4.38,-0.02,-0.45,4.42,4.46,4.30,1085285,4731.74
2,ADVICE,5.45,0.10,1.87,5.35,5.50,5.35,1022728,5559.08
3,AH,12.40,-,-,12.40,12.60,12.40,55001,688.05
4,AIT,4.84,0.02,0.41,4.86,4.86,4.82,376455,1822.59

In [15]:
df_sSET.query('Symbol == ("AH","MCS","ORI","SINGER","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
3,AH,-,12.40,-,-,12.40,12.60,12.40,-,0,55001,688.05,26900,12.40,12.50,1700
47,MCS,-,8.10,-0.05,-0.61,8.15,8.20,8.05,-,0,449562,3643.13,71900,8.05,8.10,605400
58,ORI,-,1.93,-0.05,-2.53,1.98,1.99,1.93,-,0,2099104,4097.68,166000,1.93,1.95,92900
87,SINGER,-,4.92,-0.13,-2.57,5.05,5.05,4.90,-,0,1589776,7925.88,85800,4.92,4.94,5000
101,SYNEX,-,10.00,0.10,1.01,9.90,10.10,9.90,-,0,614125,6144.21,34600,9.95,10.00,26300

In [16]:
### SETCLMV 2
file_name = "StockQuotation (2).xlsx"
input_file = os.path.join(dts_path, file_name)
df_CLMV = pd.read_excel(input_file, header=8)
df_CLMV = df_CLMV[df_CLMV['Total Volume'] != '-']
df_CLMV[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AAV,1.13,-0.04,-3.42,1.17,1.17,1.13,57725648,66212.38
1,AMATA,16.10,-0.20,-1.23,16.20,16.20,15.90,11451937,183678.55
2,BA,14.10,-0.30,-2.08,14.30,14.40,13.90,5413055,76484.75
3,BANPU,5.00,0.04,0.81,4.98,5.05,4.94,74709505,373260.94
4,BBL,165.00,-1,-0.60,167.00,167.00,163.00,8498528,1398650.50

In [17]:
df_CLMV.query('Symbol == ("BCH","IVL","PTTGC","RCL","SCC","TOA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
5,BCH,-,9.90,-0.05,-0.50,9.95,10.10,9.90,-,0.00,4641866,46179.42,628100,9.90,9.95,428900
25,IVL,-,15.20,-0.10,-0.65,15.30,15.40,15.00,-,0.00,17458918,264310.12,182900,15.10,15.20,383300
39,PTTGC,-,20.00,-0.30,-1.48,20.10,20.30,20.00,16000,320.00,9774635,196537.06,64600,20.00,20.10,95400
42,RCL,-,26.75,-0.50,-1.83,27.25,27.25,26.75,-,0.00,1888603,50885.54,68800,26.75,27.00,248000
47,SCC,-,180.50,-3.50,-1.90,183.50,186.00,180.00,9000,1624.50,3029387,551679.69,38000,180.50,181.00,21300
54,TOA,-,13.30,-,-,13.20,13.50,13.10,-,0.00,2460029,32562.00,98600,13.20,13.30,105200

In [18]:
### SETHD 3
file_name = "StockQuotation (3).xlsx"
input_file = os.path.join(dts_path, file_name)
df_HD = pd.read_excel(input_file, header=8)
df_HD = df_HD[df_HD['Total Volume'] != '-']
df_HD[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,AP,8.60,-,-,8.60,8.65,8.50,3589548,30784.18
1,BAM,7.35,-0.25,-3.29,7.55,7.60,7.35,14247503,106393.54
2,BBL,165.00,-1,-0.60,167.00,167.00,163.00,8498528,1398650.50
3,COM7,20.70,-0.50,-2.36,21.10,21.20,20.70,5356075,111883.81
4,HMPRO,6.30,-0.10,-1.56,6.30,6.40,6.25,24796993,156577.62

In [19]:
df_HD.query('Symbol == ("JMT","RCL")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
6,JMT,-,8.45,-0.35,-3.98,8.75,8.85,8.45,-,0.00,6090173,52564.86,290500,8.45,8.50,985000
19,RCL,-,26.75,-0.50,-1.83,27.25,27.25,26.75,-,0.00,1888603,50885.54,68800,26.75,27.00,248000

In [20]:
### SETESG 4
file_name = "StockQuotation (4).xlsx"
input_file = os.path.join(dts_path, file_name)
df_THSI = pd.read_excel(input_file, header=8)
df_THSI = df_THSI[df_THSI['Total Volume'] != '-']
df_THSI[colu].head()

,Symbol,Last,Change,%Change,Open,High,Low,Total Volume,Total Value (k)
0,ADVANC,305.00,-1,-0.33,307.00,309.00,304.00,4097064,1253890.25
1,AMATA,16.10,-0.20,-1.23,16.20,16.20,15.90,11451937,183678.55
2,AOT,53.00,-,-,53.50,55.75,52.75,76447306,4133907.16
3,AP,8.60,-,-,8.60,8.65,8.50,3589548,30784.18
4,AWC,2.00,-0.02,-0.99,2.02,2.04,2.00,25918325,52267.61

In [21]:
df_THSI.query('Symbol == ("AWC","BCH","IVL","JMART","JMT","NER","ORI","PTTGC","SCC","STA","SYNEX","TOA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
4,AWC,-,2.00,-0.02,-0.99,2.02,2.04,2.00,-,0.00,25918325,52267.61,4480100,2.00,2.02,240600
9,BCH,-,9.90,-0.05,-0.50,9.95,10.10,9.90,-,0.00,4641866,46179.42,628100,9.90,9.95,428900
41,IVL,-,15.20,-0.10,-0.65,15.30,15.40,15.00,-,0.00,17458918,264310.12,182900,15.10,15.20,383300
42,JMART,-,6.75,-0.15,-2.17,6.90,6.90,6.70,-,0.00,2935827,19875.88,481000,6.70,6.75,372900
43,JMT,-,8.45,-0.35,-3.98,8.75,8.85,8.45,-,0.00,6090173,52564.86,290500,8.45,8.50,985000
57,NER,-,4.32,-0.06,-1.37,4.38,4.40,4.28,-,0.00,7768250,33634.96,124200,4.30,4.32,194000
59,ORI,-,1.93,-0.05,-2.53,1.98,1.99,1.93,-,0.00,2099104,4097.68,166000,1.93,1.95,92900
68,PTTGC,-,20.00,-0.30,-1.48,20.10,20.30,20.00,16000,320.00,9774635,196537.06,64600,20.00,20.10,95400
77,SCC,-,180.50,-3.50,-1.90,183.50,186.00,180.00,9000,1624.50,3029387,551679.69,38000,180.50,181.00,21300
86,STA,-,11.70,-0.10,-0.85,11.80,11.90,11.60,-,0.00,1471168,17286.17,32800,11.60,11.70,141300
89,SYNEX,-,10.00,0.10,1.01,9.90,10.10,9.90,-,0.00,614125,6144.21,34600,9.95,10.00,26300
97,TOA,-,13.30,-,-,13.20,13.50,13.10,-,0.00,2460029,32562.00,98600,13.20,13.30,105200
104,TVO,-,21.00,-0.60,-2.78,21.60,21.60,21.00,-,0.00,2182620,46301.34,382300,21.00,21.10,300

In [22]:
### SETWB 5
file_name = "StockQuotation (5).xlsx"
input_file = os.path.join(dts_path, file_name)
df_WB = pd.read_excel(input_file, header=8)
df_WB = df_WB[df_WB['Total Volume'] != '-']
df_WB[colu].head()

  Symbol  Last Change %Change  Open  High   Low  Total Volume  Total Value (k)
0    AAV  1.13  -0.04   -3.42  1.17  1.17  1.13      57725648         66212.38
1    AOT 53.00      -       - 53.50 55.75 52.75      76447306       4133907.16
2   AURA 14.30   0.20    1.42 14.10 14.30 14.10        194352          2761.96
3     BA 14.10  -0.30   -2.08 14.30 14.40 13.90       5413055         76484.75
4    BCH  9.90  -0.05   -0.50  9.95 10.10  9.90       4641866         46179.42

In [23]:
df_WB.query('Symbol == ("BCH","CPF","STA","TVO")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
4,BCH,-,9.90,-0.05,-0.50,9.95,10.10,9.90,-,0.00,4641866,46179.42,628100,9.90,9.95,428900
16,CPF,-,20.70,-,-,20.50,20.80,20.50,-,0.00,11355416,234818.57,292900,20.60,20.70,429500
26,STA,-,11.70,-0.10,-0.85,11.80,11.90,11.60,-,0.00,1471168,17286.17,32800,11.60,11.70,141300
29,TVO,-,21.00,-0.60,-2.78,21.60,21.60,21.00,-,0.00,2182620,46301.34,382300,21.00,21.10,300

In [24]:
### PROP 6
file_name = "StockQuotation (6).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PROP = pd.read_excel(input_file, header=9)
df_PROP = df_PROP[df_PROP['Total Volume'] != '-']
df_PROP[colu].head()

   Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
1      A5  1.83  -0.01   -0.54  1.83  1.83  1.76         4916            8.92
2     AKS  0.02      -       -  0.03  0.03  0.02       395330            9.19
3   AMATA 16.10  -0.20   -1.23 16.20 16.20 15.90     11451937       183678.55
4  AMATAV  2.14  -0.02   -0.93  2.18  2.18  2.14        12200           26.44
5    ANAN  0.42  -0.01   -2.33  0.43  0.43  0.42      1060300          451.68

In [25]:
df_PROP.query('Symbol == ("AWC","ORI","SENA")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
8,AWC,-,2,-0.02,-0.99,2.02,2.04,2,-,0,25918325,52267.61,4480100,2,2.02,240600
34,ORI,-,1.93,-0.05,-2.53,1.98,1.99,1.93,-,0,2099104,4097.68,166000,1.93,1.95,92900
53,SENA,-,1.70,-0.01,-0.58,1.70,1.70,1.68,-,0,170382,288.29,3000,1.69,1.70,31500

In [26]:
### PFREIT 7
file_name = "StockQuotation (7).xlsx"
input_file = os.path.join(dts_path, file_name)
df_PFREIT = pd.read_excel(input_file, header=9)
df_PFREIT = df_PFREIT[df_PFREIT['Total Volume'] != '-']
df_PFREIT[colu].head()

    Symbol  Last Change %Change  Open  High   Low Total Volume Total Value (k)
0    AIMCG  1.73   0.01    0.58  1.75  1.75  1.72        12202           21.01
1   AIMIRT 10.40   0.10    0.97 10.30 10.40 10.30        27951          290.63
2     ALLY  4.28  -0.04   -0.93  4.32  4.32  4.22       631106         2701.80
3   AMATAR  6.60   0.05    0.76  6.60  6.70  6.55         9951           65.91
4  AXTRART 12.70   0.20    1.60 12.50 12.70 12.50       479804         6069.75

In [27]:
df_PFREIT.query('Symbol == ("AIMIRT","CPNREIT","GVREIT","WHAIR","WHART")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
1,AIMIRT,-,10.40,0.10,0.97,10.30,10.40,10.30,-,0,27951,290.63,70400,10.30,10.40,386800
9,CPNREIT,-,10.90,0.10,0.93,10.80,11,10.80,-,0,1122821,12194.85,33700,10.90,11.00,508200
17,GVREIT,-,6.55,0.10,1.55,6.45,6.55,6.45,-,0,667185,4337.96,38400,6.50,6.55,242800
54,WHAIR,-,6,-0.05,-0.83,6.05,6.10,6,-,0,263819,1596.31,295900,6.00,6.05,330100
55,WHART,-,9.75,-,-,9.75,9.80,9.70,-,0,973633,9508.58,59600,9.75,9.80,500

In [28]:
### TRANS 8
file_name = "StockQuotation (8).xlsx"
input_file = os.path.join(dts_path, file_name)
df_TRANS = pd.read_excel(input_file, header=9)
df_TRANS = df_TRANS[df_TRANS['Total Volume'] != '-']
df_TRANS[colu].head()

   Symbol Last Change %Change  Open  High   Low Total Volume Total Value (k)
0     AAV 1.13  -0.04   -3.42  1.17  1.17  1.13     57725648        66212.38
1     ANI    3      -       -     3     3  2.94        55812          165.65
2     AOT   53      -       - 53.50 55.75 52.75     76447306      4133907.16
3  ASIMAR 1.52  -0.02   -1.30  1.54  1.55  1.52        17211           26.37
4       B 0.05   0.01      25  0.04  0.05  0.04      1509087           63.14

In [29]:
df_TRANS.query('Symbol == ("RCL","TFFIF")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
19,RCL,-,26.75,-0.50,-1.83,27.25,27.25,26.75,-,0,1888603,50885.54,68800,26.75,27.00,248000
23,TFFIF,XD,6.10,-0.10,-1.61,6.10,6.10,6.05,-,0,1820349,11103.77,2793900,6.05,6.10,436200

In [30]:
### ICT 9
file_name = "StockQuotation (9).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ICT = pd.read_excel(input_file, header=9)
df_ICT = df_ICT[df_ICT['Total Volume'] != '-']
df_ICT[colu].head()

   Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0   3BBIF 6.25      -       - 6.30 6.30 6.20      3300950        20629.82
1  ADVANC  305     -1   -0.33  307  309  304      4097064      1253890.25
2     AIT 4.84   0.02    0.41 4.86 4.86 4.82       376455         1822.59
3     ALT 0.96  -0.02   -2.04    1    1 0.95       697999          673.07
4     AMR 0.41   0.01    2.50 0.40 0.42 0.39       192300           77.39

In [31]:
df_ICT.query('Symbol == ("3BBIF","DIF","JMART","SYNEX")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
0,3BBIF,-,6.25,-,-,6.30,6.30,6.20,-,0,3300950,20629.82,2801500,6.20,6.25,617400
7,DIF,-,9.25,-0.05,-0.54,9.25,9.30,9.20,-,0,7635614,70661.27,9482900,9.20,9.25,433200
19,JMART,-,6.75,-0.15,-2.17,6.90,6.90,6.70,-,0,2935827,19875.88,481000,6.70,6.75,372900
33,SYNEX,-,10,0.10,1.01,9.90,10.10,9.90,-,0,614125,6144.21,34600,9.95,10,26300

## Add section ENERG for PTG

In [33]:
### ENERG 10
file_name = "StockQuotation (10).xlsx"
input_file = os.path.join(dts_path, file_name)
df_ENG = pd.read_excel(input_file, header=9)
df_ENG = df_ENG[df_ENG['Total Volume'] != '-']
df_ENG[colu].head()

  Symbol Last Change %Change Open High  Low Total Volume Total Value (k)
0    ACC 0.36      -       - 0.36 0.37 0.35       895000          322.56
1    ACE 1.29      -       - 1.29 1.30 1.29       578805          746.72
2     AE 0.10      -       - 0.10 0.10 0.09      2191860          198.40
3    AGE 1.18   0.01    0.85 1.17 1.19 1.16       371488          435.50
4     AI    3      -       -    3 3.06    3        92975          280.75

In [34]:
df_ENG.query('Symbol == ("PTG","PTT")')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
36,PTG,-,6.90,-0.05,-0.72,6.95,7,6.85,-,0,2141570,14823.55,241600,6.90,6.95,93600
37,PTT,-,31.50,-0.25,-0.79,31.75,32,31.50,-,0,31796006,1007078.50,15324400,31.50,31.75,13946000

### ------------ End of Individual Category

In [36]:
df = pd.concat([df_S100, df_sSET, df_CLMV, df_HD, df_THSI, df_WB, df_PROP, df_PFREIT, df_TRANS, df_ICT, df_ENG])
df.shape

(678, 16)

In [37]:
df.Symbol.nunique()

373

In [38]:
df.query('Symbol == "CPNREIT"')

,Symbol,Trading Sign,Last,Change,%Change,Open,High,Low,TR Volume,TR Value (k),Total Volume,Total Value (k),Bid Size,Bid,Offer,Offer Size
9,CPNREIT,-,10.90,0.10,0.93,10.80,11,10.80,-,0,1122821,12194.85,33700,10.90,11.00,508200

In [39]:
### First equals to latest published pdf file
df = df.drop_duplicates(subset='Symbol', keep='first')
df.shape

(373, 16)

In [40]:
df.rename(columns={col: col.replace(" ", "-") for col in df.columns}, inplace=True)
df.columns

Index(['Symbol', 'Trading-Sign', 'Last', 'Change', '%Change', 'Open', 'High',
       'Low', 'TR-Volume', 'TR-Value-(k)', 'Total-Volume', 'Total-Value-(k)',
       'Bid-Size', 'Bid', 'Offer', 'Offer-Size'],
      dtype='object')

In [41]:
cols = 'Symbol Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
#df[cols].sort_values('Symbol',ascending=True)
df[cols].shape

(373, 9)

In [42]:
# Clean Symbol column (remove <XD>)
df['Symbol'] = df['Symbol'].str.replace(r'\s*<.*?>', '', regex=True)

# Then proceed with numeric conversion as above
numeric_cols = df.columns.drop('Symbol')
df[numeric_cols] = (
    df[numeric_cols].replace('-', 0)
    .apply(pd.to_numeric, errors='coerce', downcast=None)  # Disable downcasting
)
df[cols].shape

C:\Users\PC1\AppData\Local\Temp\ipykernel_98968\3393296708.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[numeric_cols].replace('-', 0)

(373, 9)

In [43]:
# If run after actual work day
#today = today - timedelta(days=2)
#today

In [44]:
df.insert(1, 'Date', today)

In [45]:
colt = 'Symbol Date Last Change %Change Open High Low Total-Volume Total-Value-(k)'.split()
df[colt]

,Symbol,Date,Last,Change,%Change,Open,High,Low,Total-Volume,Total-Value-(k)
0,AAV,2025-12-08,1.13,-0.04,-3.42,1.17,1.17,1.13,57725648,66212.38
1,ADVANC,2025-12-08,305.00,-1.00,-0.33,307.00,309.00,304.00,4097064,1253890.25
2,AEONTS,2025-12-08,96.25,0.50,0.52,96.00,97.75,95.75,270550,26139.12
3,AMATA,2025-12-08,16.10,-0.20,-1.23,16.20,16.20,15.90,11451937,183678.55
4,AOT,2025-12-08,53.00,0.00,0.00,53.50,55.75,52.75,76447306,4133907.16
...,...,...,...,...,...,...,...,...,...,...
54,TGE,2025-12-08,1.28,0.00,0.00,1.28,1.29,1.24,58901,74.86
56,TPIPP,2025-12-08,1.81,0.01,0.56,1.80,1.84,1.80,2854345,5184.87
57,TSE,2025-12-08,0.48,0.00,0.00,0.48,0.49,0.47,543156,259.73
59,UBE,2025-12-08,0.43,0.00,0.00,0.43,0.44,0.43,1038000,446.66
61,WP,2025-12-08,3.78,0.00,0.00,3.76,3.78,3.76,37233,140.72

In [46]:
file_name = "name-ttl.csv"
input_file = os.path.join(dat_path, file_name)
print(f"Input file: {input_file}")

Input file: C:\Users\PC1\OneDrive\A5\Data\name-ttl.csv

In [47]:
df_name = pd.read_csv(input_file, header=None, names=['Symbol'])
df_name.shape

(215, 1)

In [48]:
df_out = df[colt]
df_out.shape

(373, 10)

In [49]:
df_merge = pd.merge(df_name, df_out, on = 'Symbol', how='inner')
df_merge.shape

(168, 10)

In [50]:
df_merge.columns = df_merge.columns.str.lower()
df_merge.columns

Index(['symbol', 'date', 'last', 'change', '%change', 'open', 'high', 'low',
       'total-volume', 'total-value-(k)'],
      dtype='object')

In [51]:
df_merge.rename(columns={'symbol':'name','last':'price','total-volume':'volume',
                         'total-value-(k)':'value(m)'},inplace=True)
df_merge.columns

Index(['name', 'date', 'price', 'change', '%change', 'open', 'high', 'low',
       'volume', 'value(m)'],
      dtype='object')

In [52]:
colp = 'name date price high low volume open'.split()

file_name = "Price.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [53]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A5\Data\Price.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price.csv

In [54]:
df_merge[colp].to_csv(output_file, header=True, index=False)
df_merge[colp].to_csv(god_file, header=True, index=False)
df_merge[colp].to_csv(icd_file, header=True, index=False)
df_merge[colp].to_csv(osd_file, header=True, index=False)

### End of daily process to export Price to MySql Stock database

In [56]:
file_name = "Price-Today.csv"
output_file = os.path.join(dat_path, file_name)
god_file = os.path.join(god_path, file_name)
icd_file = os.path.join(icd_path, file_name)
osd_file = os.path.join(osd_path, file_name)

In [57]:
print(f"output_file : {output_file}") 
print(f"icd_file : {icd_file}") 
print(f"god_file : {god_file}") 
print(f"osd_file : {osd_file}")

output_file : C:\Users\PC1\OneDrive\A5\Data\Price-Today.csv
icd_file : C:\Users\PC1\iCloudDrive\Data\Price-Today.csv
god_file : C:\Users\PC1\OneDrive\Imports\santisoontarinka@gmail.com - Google Drive\Data\Price-Today.csv
osd_file : C:\Users\PC1\OneDrive\Documents\obsidian-git-sync\Data\Price-Today.csv

In [58]:
df_merge.to_csv(output_file, header=True, index=False)
df_merge.to_csv(god_file, header=True, index=False)
df_merge.to_csv(icd_file, header=True, index=False)
df_merge.to_csv(osd_file, header=True, index=False)

In [59]:
# Get the current time
current_time = datetime.now()
# Format the time to remove milliseconds
formatted_time = current_time.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_time)

2025-12-08 19:59:47

### End of daily process to export Price-Today for Market-all, Create Dailies & Daily out processes